version: "3"

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env_docker
    ports:
      - "3000:3000"

